/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.project.horas.view;

import com.project.horas.controller.HorasController;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

/**
 *
 * @author Pablo Presa
 */
public class PanelJornadaActual extends javax.swing.JFrame {

    HorasController controller;
    
    Timer stopwatch;

    int count = 0;
    int delay = 1000;

    public PanelJornadaActual(HorasController controller) {
        this.controller = controller;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTiempoTranscurrido = new javax.swing.JLabel();
        btnTerminarJornada = new javax.swing.JButton();
        txtTiempoTranscurrido1 = new javax.swing.JLabel();
        lblTiempoTranscurrido = new javax.swing.JLabel();
        lblHoraEntrada = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        btnVerHoras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtTiempoTranscurrido.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtTiempoTranscurrido.setText("Tiempo transcurrido");

        btnTerminarJornada.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnTerminarJornada.setText("Terminar Jornada");
        btnTerminarJornada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTerminarJornadaActionPerformed(evt);
            }
        });

        txtTiempoTranscurrido1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtTiempoTranscurrido1.setText("Hora entrada");

        lblTiempoTranscurrido.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTiempoTranscurrido.setText("---");

        lblHoraEntrada.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblHoraEntrada.setText("---");

        btnSalir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnVerHoras.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnVerHoras.setText("Ver Horas");
        btnVerHoras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerHorasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(txtTiempoTranscurrido1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(btnSalir))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btnVerHoras, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnTerminarJornada)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblTiempoTranscurrido, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(94, 94, 94))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(txtTiempoTranscurrido, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(lblHoraEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(txtTiempoTranscurrido1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblHoraEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(txtTiempoTranscurrido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTiempoTranscurrido, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTerminarJornada, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnVerHoras, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTerminarJornadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTerminarJornadaActionPerformed
        controller.terminarJornada(this);
    }//GEN-LAST:event_btnTerminarJornadaActionPerformed

    private void btnVerHorasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerHorasActionPerformed
       controller.verHoras(null, this, null);
    }//GEN-LAST:event_btnVerHorasActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        controller.salir(null, null, this, null);
    }//GEN-LAST:event_btnSalirActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnTerminarJornada;
    private javax.swing.JButton btnVerHoras;
    private javax.swing.JLabel lblHoraEntrada;
    private javax.swing.JLabel lblTiempoTranscurrido;
    private javax.swing.JLabel txtTiempoTranscurrido;
    private javax.swing.JLabel txtTiempoTranscurrido1;
    // End of variables declaration//GEN-END:variables

    public void setHoraEntrada(String horaActual) {
        lblHoraEntrada.setText(horaActual);
    }
    
    public void agregarSegundo(){

                String tiempoActual = lblTiempoTranscurrido.getText();
                String[] horaMinutoSegundo = tiempoActual.split(":");
        
                String horaActual = horaMinutoSegundo[0];
                String minutoActual = horaMinutoSegundo[1];
                String segundoActual = horaMinutoSegundo[2];
        
        boolean horaMas = false;
        boolean minutoMas = false;

        int iSegundo = 0;
        int iMinuto = 0;
        int iHora = 0;
        
        try{
            iSegundo = Integer.parseInt(segundoActual);
            if(iSegundo==59){
                iSegundo=0;
                minutoMas = true;
            }
            else{
                iSegundo++;
            }
        
            iMinuto = Integer.parseInt(minutoActual);
            if(iMinuto==59){
                iMinuto=0;
                horaMas = true;
            }
            
            iHora = Integer.parseInt(horaActual);
            if(horaMas){
                iHora++;
            }
            if(minutoMas){
                iMinuto++;
            }
        }
        catch(Exception e){}
        
        lblTiempoTranscurrido.setText(darHora(iHora, iMinuto, iSegundo));
    }
    
    private String darHora(int hora, int minuto, int segundo){
        
            String sHora = (hora>=10)? hora+"" : "0"+hora;
            String sMinuto = (minuto>=10)? minuto+"" : "0"+minuto;
            String sSegundo = (segundo>=10)? segundo+"" : "0"+segundo;
        
            return sHora+":"+sMinuto+":"+sSegundo;
    }
    
  public void setTiempoTranscurrido(String tiempoTranscurrido){
      lblTiempoTranscurrido.setText(tiempoTranscurrido);
      startTimer(60);
  }
  
  //startTimer(60); this is how to instantiate the timer method for 60 secs

    public void startTimer(int countPassed){
        ActionListener action = new ActionListener(){
            public void actionPerformed(ActionEvent e){
                    agregarSegundo();
            }
        };
        stopwatch = new Timer(delay, action);
        stopwatch.setInitialDelay(0);
        stopwatch.start();
    }
    
}



